#!/usr/bin/env bash

# Define os pacotes que serão instalados
PACOTES_BASE="xfce4 xorg lightdm-webkit2-greeter lightdm-gtk-greeter lightdm-gtk-greeter-settings linux-lts-headers "
PACOTES_MULTIMIDIA="ffmpeg vlc"
PACOTES_THUNAR="thunar-archive-plugin thunar-media-tags-plugin thunar-shares-plugin thunar-vcs-plugin"
PACOTES_SISTEMA="python python-pip android-tools wget network-manager-applet xdg-user-dirs pavucontrol gvfs gvfs-mtp  blueman bluez bluez-utils usbutils nano git curl fastfetch plank dosfstools gparted ark htop gedit"

echo "Script de instalação padrão xfce"

echo "Atualizando o sistema..."
sudo pacman -Syu

echo "Sistema atualizado."

echo "Iniciando a instalação dos pacotes..."

sudo pacman -S $PACOTES_BASE $PACOTES_MULTIMIDIA $PACOTES_THUNAR $PACOTES_SISTEMA

echo "Instalação de pacotes concluída."

echo "Iniciando a configuração do pacman.conf..."

# Descomenta a seção [multilib]
sudo sed -i 's/#\[multilib\]/\[multilib\]/g' /etc/pacman.conf

# Descomenta a linha Include
sudo sed -i 's/#Include = \/etc\/pacman.d\/mirrorlist/Include = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf

echo "pacman.conf configurado com sucesso!"

echo "Atualizando novamente o Sistema"
sudo pacman -Syu

echo "Instalando yay"
mkdir -p .Aur 
cd .Aur
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

echo "Voltando pro home"
cd ~/

echo "Instalando drives da gtx550ti via reporitorio Arch (Aur)"
 
yay -S --noconfirm nvidia-390xx-dkms nvidia-390xx-utils nvidia-390xx-settings lib32-nvidia-390xx-utils

echo "Instalação de drives concluida!"

echo "Colocando o Noveau em blacklist"
echo "blacklist nouveau" | sudo tee /etc/modprobe.d/blacklist-nouveau.conf > /dev/null
  
echo "Gerando initramfs"
sudo mkinitcpio -P
 
echo "Criando configuração xorg Nvidia"
sudo nvidia-xconfig
 
echo "Alterando xconfig xorg pra config basica"
cd /etc/X11/
sudo rm xorg.conf
curl -O https://raw.githubusercontent.com/MacacoDev404/XFce-Install/refs/heads/main/xorg.conf

echo "Configurando fastfetch"
mkdir -p .config/fastfetch
mv config.jsonc .config/fastfetch

echo "Configurando Opera"
mv opera ~/.config

echo "Configurando o nano"
mv .nanorc ~/

echo "Removendo Lixos"
sudo rm -rf .Aur

echo "Reiniciando o Sistema em 5 Segundos"
sleep 5
sudo reboot

